name: Build, Test, and Publish Python Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-test-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          pip install -e .[dev]
          pip install bump2version

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Run tests
        run: |
          pytest tests/

      - name: Bump version and push tags
        if: github.ref == 'refs/heads/main' && success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bump2version patch  # 'patch' 'minor','major'
          git push --follow-tags

      - name: Build package
        if: github.ref == 'refs/heads/main' && success()
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish package to PyPI
        if: github.ref == 'refs/heads/main' && success()
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload dist/*

